#!/usr/bin/env zsh
zmodload zsh/zprof


# ====== .zshrc ======
# sourced in interactive shells. should set 
# - aliases
# - functions,
# - options
# - key bindings,
# - etc.


# There are 5 startup files that zsh reads commands from:
# .zshenv - FUNCTIONS (UNI) and environment variables go here
# .zprofile
# .zshrc
# .zlogin
# .zlogout


# ========== useful keyboard shortcuts ==================
# ctrl-A - beginning of line
# ctrl-E - end of line
# ctrl-W - delete previous word


# put this before the instant prompt preamble to avoid error messages when creating new sessions
# https://direnv.net/docs/hook.html
# https://github.com/direnv/direnv/wiki
eval "$(direnv hook zsh)"

#  ======== P10K INSTANT PROMPT ========================
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# ========== CHEZMOI ==================================
# omz is imported by chezmoi, disabling autoupdate prevents the omz directory getting
# out of sync with chezmoi. It will still be updated when running `cm apply` and the cache (1 week)
# has expired.
DISABLE_AUTO_UPDATE="true"


# ============= PLUGINS =============================
plugins=(
    autopep8 # completion for the pep8 tool
    # aws # some performance costs. disable if not using.
    brew # completion for brew commands, adds alias `brews`
    chucknorris # commands `chuck` and `chuck_cow`
    colored-man-pages # yep
    colorize # more syntax highlighting
    docker
    docker-compose
    extract # `extract` any archive. `extract -r <file>` remove orig archive file
    fzf # fuzzy find
    git # adds git aliases and completions
    # heroku
    # kubectl
    # minikube
    pep8 # completion for pep8 python coding style
    pip # completion for pip commands
    vi-mode # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode
    zsh-autosuggestions
    zsh-syntax-highlighting
    # zsh-vi-mode # https://github.com/jeffreytse/zsh-vi-mode
)

ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER=john
VIRTUAL_ENV_DISABLE_PROMPT=0
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
GIT_AUTO_FETCH_INTERVAL=60 # in seconds

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Set personal aliases, overriding those provided by oh-my-zsh libs, plugins, and themes.
# Aliases can be placed here, though oh-my-zsh users are encouraged to define aliases 
# within the ZSH_CUSTOM folder.
source ~/.aliases 

# source ~/.fzf.zsh if it exists
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
# export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -f -g ""'

# Solarized colors
export FZF_DEFAULT_OPTS='
    --color fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229
    --color info:150,prompt:110,spinner:150,pointer:167,marker:174
'

if [ "$(uname)" = "Darwin" ]; then
    # source iterm2_shell_integrations if is exists
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

    # this makes the z command work
    . $(brew --prefix)/etc/profile.d/z.sh

    # broot cli tool - see a big dir on one screen
    [[ ! -f /Users/$USER/.config/broot/launcher/bash/br ]] || source /Users/$USER/.config/broot/launcher/bash/br 
    [[ ! -f /Users/$USER/Library/Preferences/org.dystroy.broot/launcher/bash/br ]] || source /Users/$USER/Library/Preferences/org.dystroy.broot/launcher/bash/br 

    # kubernetes
    source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
    PS1='$(kube_ps1)'$PS1

    # Google Cloud Platform (GCP) shell command completion - use it instead of the plugin because this is updated more frequently
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

    # colors for ls commands
    source ~/.zsh/zsh-dircolors-solarized/zsh-dircolors-solarized.zsh
fi

# pyenv - see ~/.zprofile for PATH modifications
eval "$(pyenv init -)"

# colorful less
LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R -X -F '
# export LESSOPEN='|~/.lessfilter %s'

# tab-space complete autosuggestions
bindkey '^I ' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

# https://github.com/jeffreytse/zsh-vi-mode#custom-escape-key
# Only changing the escape key to `jk` in insert mode, we still
# keep using the default keybindings `^[` in other modes
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

# vi-mode
# bindkey -v
bindkey "jk" vi-cmd-mode

bindkey "^k" up-line-or-search
bindkey "^j" down-line-or-search
bindkey "^h" backward-word
bindkey "^l" forward-word

# suspend a half-written command
# https://unix.stackexchange.com/questions/10825/remember-a-half-typed-command-while-i-check-something
# https://sgeb.io/posts/bash-zsh-half-typed-commands/
bindkey "^q" push-line-or-edit

# make z command work
. "$(brew --prefix)/etc/profile.d/z.sh"

# make compinit a bit faster by only checking the cache once per day
# https://htr3n.github.io/2018/07/faster-zsh/
autoload -Uz compinit
if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

# Vagrant command completion
fpath=(/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/contrib/zsh $fpath)

# zsh-histdb plugin - https://github.com/larkery/zsh-histdb
HISTDB_TABULATE_CMD=(sed -e $'s/\x1f/\t/g')
source $HOME/.oh-my-zsh/custom/plugins/zsh-histdb/sqlite-history.zsh
autoload -Uz add-zsh-hook

# zprof
