#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh
#
# ====== .zshrc ======
# sourced in interactive shells. should set 
# 	- aliases
# 	- functions,
# 	- options
# 	- key bindings,
# 	- etc.

# There are 5 startup files that zsh reads commands from:
#     .zshenv - PATH settings go here
#     .zprofile
#     .zshrc
#     .zlogin
#     .zlogout

# === useful keyboard shortcuts =====
# ctrl-A - beginning of line
# ctrl-E - end of line
# ctrl-W - delete previous word

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
    colorize # more syntax highlighting
    brew # completion for brew commands, adds alias `brews`
    extract # `extract` any archive. `extract -r <file>` remove orig archive file
    fzf # fuzzy find
    pip # completion for pip commands
    pep8 # completion for pep8 python coding style
    django # adds completion for django manage.py commands
    git # adds git aliases and completions https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git/
    chucknorris # commands `chuck` and `chuck_cow`
    docker
    docker-compose
    kubectl
    minikube
    heroku
    aws
    colored-man-pages # yep
    autopep8 # completion for the pep8 tool
    zsh-autosuggestions
    zsh-syntax-highlighting
    vi-mode # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vi-mode
    # zsh-vi-mode # https://github.com/jeffreytse/zsh-vi-mode
)

ZSH_THEME="powerlevel10k/powerlevel10k"
DEFAULT_USER=john
VIRTUAL_ENV_DISABLE_PROMPT=0
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Set personal aliases, overriding those provided by oh-my-zsh libs, plugins, and themes.
# Aliases can be placed here, though oh-my-zsh users are encouraged to define aliases 
# within the ZSH_CUSTOM folder.
source ~/.aliases 

# source ~/.fzf.zsh if it exists
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
# export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -f -g ""'

# Solarized colors
export FZF_DEFAULT_OPTS='
    --color fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229
    --color info:150,prompt:110,spinner:150,pointer:167,marker:174
'

if [ "$(uname)" = "Darwin" ]; then
    # source iterm2_shell_integrations if is exists
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

    # ========= zone of uncertainty =========
    # WSL make autosuggestions work
    # ZSH_DISABLE_COMPFIX=true

    # what is this ?
    # zmodload zsh/zprof

    # ====== end of zone of uncertainty ======


    # this makes the z command work
    . $(brew --prefix)/etc/profile.d/z.sh
    # broot cli tool - see a big dir on one screen
    # source /Users/$USER/Library/Preferences/org.dystroy.broot/launcher/bash/br
    source /Users/$USER/.config/broot/launcher/bash/br
    # virtualenv wrapper for pyenv ?
    source /usr/local/bin/virtualenvwrapper_lazy.sh

    # kubernetes
    source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
    PS1='$(kube_ps1)'$PS1

    # Git completion I think this isn't needed if you load the plugin also
    zstyle ':completion:*:*:git:*' script "${HOME}/projects/.dotfiles/git-completion.bash"
    fpath=(~/.zsh $fpath)

    # Google Cloud Platform (GCP) shell command completion - use it instead of the plugin because this is updated more frequently
    source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

    # AZURE completion - needed cos there isn't a plugin
    # autoload bashcompinit && bashcompinit
    # source /usr/local/Cellar/azure-cli/2.22.1/etc/bash_completion.d/az
    # source /usr/local/Cellar/azure-cli/2.22.1/etc/bash_completion.d/

    # create virtual environments using pyenv rather than virtualenv.
    # https://medium.freecodecamp.org/manage-multiple-python-versions-and-virtual-environments-venv-pyenv-pyvenv-a29fb00c296f
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    # colors for ls commands
    source ~/.zsh/zsh-dircolors-solarized/zsh-dircolors-solarized.zsh
fi

# if [ "$(uname)" = "Linux" ]; then
#     source /home/$(whoami)/Library/Preferences/org.dystroy.broot/launcher/bash/br
# fi

# colorful less
export LESS='-R'
export LESSOPEN='|~/.lessfilter %s'

# tab-space complete autosuggestions
bindkey '^I ' autosuggest-accept
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=5'

# https://github.com/jeffreytse/zsh-vi-mode#custom-escape-key
# Only changing the escape key to `jk` in insert mode, we still
# keep using the default keybindings `^[` in other modes
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

# vi-mode
# bindkey -v
bindkey "jk" vi-cmd-mode

# fzf_history_seach() {
#     BUFFER=$(history -t '%Y-%m-%d %H:%M:%S' 0 | fzf +s +m -x --tac -e -q "$BUFFER" | awk '{print substr($0, index($0, $4))}' | awk '!seen[$4, $5, $6, $7, $8, $9, $10]++' | awk '{print substr($0, index($0, $4))}' )
#   zle end-of-line
# }
# autoload fzf_history_seach
# zle -N fzf_history_seach
# bindkey '^r' fzf_history_seach

bindkey "^k" up-line-or-search
bindkey "^j" down-line-or-search
bindkey "^h" backward-word
bindkey "^l" forward-word

bindkey "^p" push-line-or-edit

. "$(brew --prefix)/etc/profile.d/z.sh"

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)
