#!/usr/bin/env sh


alt - f : yabai -m window --toggle zoom-fullscreen
alt - n : yabai -m space --create; id="$(yabai -m query --spaces --display | jq '.[-1].index')"; yabai -m window --space $id; yabai -m space --focus $id
alt - c : yabai -m window --toggle float; yabai -m window --grid 4:4:1:1:2:2
alt - t : yabai -m window --toggle float

# Navigation
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Go to space
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6

# Move app to workspace and follow
# meh 
alt + shift + ctrl - 1 : yabai -m window --space 1; yabai -m space --focus 1
alt + shift + ctrl - 2 : yabai -m window --space 2; yabai -m space --focus 2
alt + shift + ctrl - 3 : yabai -m window --space 3; yabai -m space --focus 3
alt + shift + ctrl - 4 : yabai -m window --space 4; yabai -m space --focus 4
alt + shift + ctrl - 5 : yabai -m window --space 5; yabai -m space --focus 5
alt + shift + ctrl - 6 : yabai -m window --space 6; yabai -m space --focus 6

# Move focus container to workspace, but _dont_ follow
alt + shift - 1 : yabai -m window --space 1
alt + shift - 2 : yabai -m window --space 2
alt + shift - 3 : yabai -m window --space 3
alt + shift - 4 : yabai -m window --space 4
alt + shift - 5 : yabai -m window --space 5
alt + shift - 6 : yabai -m window --space 6

# Moving windows
alt + shift - h : yabai -m window --warp west
alt + shift - j : yabai -m window --warp south
alt + shift - k : yabai -m window --warp north
alt + shift - l : yabai -m window --warp east


# Resize windows
alt + ctrl - h : yabai -m window --resize left:-100:0 ; yabai -m window --resize right:-100:0
alt + ctrl - j : yabai -m window --resize bottom:0:100 ; yabai -m window --resize top:0:100
alt + ctrl - k : yabai -m window --resize top:0:-100 ; yabai -m window --resize bottom:0:-100
alt + ctrl - l : yabai -m window --resize right:100:0 ; yabai -m window --resize left:100:0


# Set insertion point for focused container, then open something 
alt + shift + ctrl - h : yabai -m window --insert west
alt + shift + ctrl - j : yabai -m window --insert south
alt + shift + ctrl - k : yabai -m window --insert north
alt + shift + ctrl - l : yabai -m window --insert east



