#!/usr/bin/env sh

# keep this at the top. SIP needs to be disabled in mojave specific way. Dont delete it.
# ===========================================================================================
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# !*!*! THE KEYBOARD COMMANDS THEMSELVES ARE IN SKHD/SKHDRC !*!*!


# ===========================================================================================
# YABAI CONFIGURATION
# ===========================================================================================

yabai -m config layout                       bsp

yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5

yabai -m config split_ratio                  0.5
yabai -m config window_topmost               on
yabai -m config mouse_follows_focus          on
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
# on or off (default: off)
yabai -m config auto_balance off

yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff39FF14
yabai -m config normal_window_border_color   0xf33acfff

yabai -m config window_gap                   5
yabai -m config window_shadow                on
yabai -m config window_opacity               off

yabai -m config window_placement            second_child


# ===========================================================================================
# SPACES & APPS CONFIGURATION 
# ===========================================================================================
echo "\nConfiguring Yabai.."

# https://d12frosted.io/posts/2022-04-23-yabai-spaces.html - use it like `setup_space 4 social`
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 iterm
setup_space 2 web
setup_space 3 web
setup_space 4 social
setup_space 5 email
setup_space 6 calendar
setup_space 7 messages

# clean up spaces with index greater than $MAX_SPACES
for idx in $(yabai -m query --spaces | jq '.[].index | select(. > 6)' | sort -nr); do
  yabai -m space --destroy "$idx"
done

# setup applications on startup
yabai -m rule --add app="^iTerm$" space=^1
yabai -m rule --add app="^Firefox$" space=2
yabai -m rule --add app="^Chrome$" space=3
yabai -m rule --add app="^Notes$" space=4
yabai -m rule --add app="^WhatsApp$" space=4
yabai -m rule --add app="^Messages$" space=4
yabai -m rule --add app="^Mimestream$" space=5
yabai -m rule --add app="^Calendar$" space=6
yabai -m rule --add app="^Slack$" space=7
yabai -m rule --add app="^Microsoft Teams$" space=7

# floating normal windows
yabai -m rule --add app="^System Preferences$" manage=off

echo "Configuration complete."
